name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          sudo apt update
          sudo apt install llvm-12
      - name: Configure
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D SANITIZERS=ON -D LLVM_DIR=/usr/lib/llvm-12/cmake -G Ninja
      - name: Build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cd build && ctest
